apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster1-apps
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://github.com/jfr992/argocd-playground-agents.git
    targetRevision: main
    path: cluster1/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy: {}
