apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-watcher
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: "."
spec:
  project: argocd
  source:
    repoURL: 'https://github.com/jfr992/argocd-playground-migration.git'
    targetRevision: main
    path: clusters/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy: 
    # automated:
    #   prune: true
    #   selfHeal: true