apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx2
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://github.com/jfr992/argocd-playground-agents.git
    targetRevision: main
    path: cluster1/argocd/nginx2/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy: {}
